// Code generated by MockGen. DO NOT EDIT.
// Source: ./commons/interfaces/currency.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCurrencyRepo is a mock of CurrencyRepo interface.
type MockCurrencyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRepoMockRecorder
}

// MockCurrencyRepoMockRecorder is the mock recorder for MockCurrencyRepo.
type MockCurrencyRepoMockRecorder struct {
	mock *MockCurrencyRepo
}

// NewMockCurrencyRepo creates a new mock instance.
func NewMockCurrencyRepo(ctrl *gomock.Controller) *MockCurrencyRepo {
	mock := &MockCurrencyRepo{ctrl: ctrl}
	mock.recorder = &MockCurrencyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRepo) EXPECT() *MockCurrencyRepoMockRecorder {
	return m.recorder
}

// GetIDR mocks base method.
func (m *MockCurrencyRepo) GetIDR() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDR")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDR indicates an expected call of GetIDR.
func (mr *MockCurrencyRepoMockRecorder) GetIDR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDR", reflect.TypeOf((*MockCurrencyRepo)(nil).GetIDR))
}
